router:
  host: 192.168.1.1
  username: root
  password: ${ROOTER_PASS}
  ssh_port: 22
  luci_port: 80
  use_ssh: false
  jellyfin_ip: 192.168.1.243

jellyfin:
  host: 192.168.1.243
  port: 8096
  api_key: ${JELLY_API}
  use_https: false

network:
  internal_ranges:
    - "192.168.1.0/24"
    - "10.0.0.0/8"
  test_mode: false
  test_external_ranges:
    - "203.0.113.0/24"

bandwidth:
  algorithm: equal_split
  min_per_user: 2.0
  max_per_user: 50.0
  reserved_bandwidth: 10.0
  total_upload_mbps: 100.0
  # Duration (in minutes) used to average bandwidth usage
  spike_duration: 3
  # When non-Jellyfin bandwidth is below this threshold (Mbps),
  # users share bandwidth equally up to max_per_user
  low_usage_threshold: 20.0

daemon:
  update_interval: 30
  log_level: INFO
  log_file: jellydemon.log
  log_max_size: 10MB
  log_backup_count: 5
  dry_run: false
  backup_user_settings: true
  pid_file: /tmp/jellydemon.pid
